### ISSUE TITLE
Admin panel?

### ISSUE THREAD

**Issue by axeberg** [chas-academy/berserkers-06-imdb-clone#148]
I'm missing information or instructions on how to access your admin panel.

**Comment by ghost** [comment]
This issue weren´t used later, quite confusing what people should do in
this Project.

2018-02-28 11:10 GMT+01:00 Axel Olsson <notifications@github.com>:

**Comment by SebastianGerS** [comment]
@axelolsson I have now allowed access for your user aolsson so that you can access the admin panel, sorry for the lack of information.
A new menu item should apeer when you login (atleast on desktop we hade som issues whith the mobile menu).
In the admin panel you can add movies/series to the database and change other users status

**Comment by ghost** [comment]
Awesome and sorry for my response earlier ^^

2018-02-28 12:01 GMT+01:00 SebastianGerS <notifications@github.com>:
